# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1fd17b7c73e6365243e427efde04ced22566e179d038df44f81d288b3495b1176e90c089ec10154a884b63a7f9d052764c0a98aa81a718c373c8dc7c84f1556

test:
  secret_key_base: bb4bb78787dc85256c7019e2917cbb4522326197a66c376e8b82fa7d7dea5f451ab5f8524499a2703bd3c9ff81c618ce606b9152dfde05014f31f37fc41962d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
